language: cpp
before_script:
- sudo apt-get install graphviz
- sudo apt-get install doxygen
script:
- cmake .
- cmake --build .
- cmake --build . --target package
- doxygen $TRAVIS_BUILD_DIR/Doxyfile
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
